export const items = [
    { id: 1, title: 'Name', description: 'Primary Tag', imageUrl: 'https://via.placeholder.com/300' },
    { id: 2, title: 'Name', description: 'Primary Tag', imageUrl: 'https://via.placeholder.com/300' },
    { id: 3, title: 'Name', description: 'Primary Tag', imageUrl: 'https://via.placeholder.com/300' },
    { id: 3, title: 'Name', description: 'Primary Tag', imageUrl: 'https://via.placeholder.com/300' },
    { id: 3, title: 'Name', description: 'Primary Tag', imageUrl: 'https://via.placeholder.com/300' },
    { id: 3, title: 'Name', description: 'Primary Tag', imageUrl: 'https://via.placeholder.com/300' },
    { id: 3, title: 'Name', description: 'Primary Tag', imageUrl: 'https://via.placeholder.com/300' },
    { id: 3, title: 'Name', description: 'Primary Tag', imageUrl: 'https://via.placeholder.com/300' },
    { id: 3, title: 'Name', description: 'Primary Tag', imageUrl: 'https://via.placeholder.com/300' },
    { id: 3, title: 'Name', description: 'Primary Tag', imageUrl: 'https://via.placeholder.com/300' },
    { id: 3, title: 'Name', description: 'Primary Tag', imageUrl: 'https://via.placeholder.com/300' },
    { id: 3, title: 'Name', description: 'Primary Tag', imageUrl: 'https://via.placeholder.com/300' },
    { id: 3, title: 'Name', description: 'Primary Tag', imageUrl: 'https://via.placeholder.com/300' },
    { id: 3, title: 'Name', description: 'Primary Tag', imageUrl: 'https://via.placeholder.com/300' },
    { id: 3, title: 'Name', description: 'Primary Tag', imageUrl: 'https://via.placeholder.com/300' },
    { id: 3, title: 'Name', description: 'Primary Tag', imageUrl: 'https://via.placeholder.com/300' },
    { id: 3, title: 'Name', description: 'Primary Tag', imageUrl: 'https://via.placeholder.com/300' },
    { id: 3, title: 'Name', description: 'Primary Tag', imageUrl: 'https://via.placeholder.com/300' },
    { id: 3, title: 'Name', description: 'Primary Tag', imageUrl: 'https://via.placeholder.com/300' },
    // Add more items as needed
  ];